server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ato_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: jgo
    password: Jgo@1645
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect


  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update