server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ato_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: Id
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL

  data:
    redis:
      port: 6379
      host: 127.0.0.1
